name: Github actions

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        pip install -r requirememnts.txt

      - name: Run unit test
        run: coverage run -m pytest && coverage report
